### ISSUE TITLE
remote backup

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/backup#4] opened 2017-03-26 17:10 UTC
It should be possible to automatically push password protected backups to other Nextclouds for remote backup

**Comment by GoetheG** [comment] 2018-06-07 14:11
Good point. I wish there were an easier way to make backups. For example for people without knowledge in coding.

**Comment by ArtificialOwl** [comment] 2021-09-29 20:25
done, just need encryption (duplicate of #3)

**Closed by ArtificialOwl** 2021-09-29 20:25 UTC
