### ISSUE TITLE
Please keep a changelog

### ISSUE THREAD

**Issue by nursoda** [nextcloud/backup#373] opened 2022-07-22 12:01 UTC
Thank you for developing a decent Backup app for Nextcloud, but please let users/admins know what changed prior to installing a new version. As far as I can see, CHANGELOG stalled at 1.0.5, there is not release within Github (so no notes there either), no notes in the app store nor in the app description itself (which then would be visible in the NC instance when showing the app details page).

**Comment by solracsf** [comment] 2022-09-01 10:23
Close as duplicate of https://github.com/nextcloud/backup/issues/410
(see there for more info too, thanks)

**Closed by solracsf** 2022-09-01 10:23 UTC
